name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-check:
    name: Security Check
    run-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: securego/gosec@master
        with:
          args: ./...
  test:
    name: Test
    needs: [ security-check ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.17
      - run: |
          go get -v -t -d ./...
      - run: |
          go test -v ./...
